ECE479 LAB 1: Python, NumPy and Data Analytics Basics
====================================

**Report Due: Feb 13, 11:59 PM**

In LAB 1, you will learn the basics of Python programming and the NumPy library by practicing basic image processing operations, including image cropping, Gaussian Filtering, and up/downsampling. In addition, you will have to implement two classical data analytics algorithms with Python and NumPy.

If you do not have Python programming experience before, you can use the below links for a quick tutorial.

Python tutorial: https://docs.python.org/3.9/tutorial/

Python: How to fetch internet resources using urllib:
https://docs.python.org/3/howto/urllib2.html


## PART I: Python Basics: NumPy

NumPy is a foundational library in python that works with numbers and arrays. We will be using NumPy extensively to work with array computations in the following labs. Before we start, please check if you have successfully installed the Numpy package. NumPy [Tutorial][link_numpy_start] is available for your reference. (All blue words have hyperlinks embedded for your convenience.)

[link_numpy_start]: https://docs.scipy.org/doc/numpy/user/quickstart.html

To install dependencies for lab1, please use "pip install -r requirements.txt", or manually install all packages listed in the "requirement.txt" file.

Once you are ready, please complete the following tasks: 
(NOTE: In the following tasks, you are **NOT** allowed to use explicit `for` loops. Each task should only require very few lines of code.)

  * **Step 1**: Generate a 2-D all-zero NumPy array **A**, with the size of 9 x 6 (row x column). Print the type and shape of **A**.  
  Hint: `type(A)`returns the type of an object `A`.
  * **Step 2**: Create a block-I shape by replacing certain elements from 0 to 1 in array **A**.
  * **Step 3**: Generate a 2-D array **B** by filling zero-vector at the top and bottom of the array **A**.
  
  ![sec1_img](figures/block-I.png)
  
  * **Step 4**: Generate a 2-D array **C**, with numbers 1, 2, 3, ..., 65, 66 filled in row by row, starting from the top-left corner of the array. The size of **C** is 11 x 6 (row x column, the same size as array **B**).
  * **Step 5**: Perform element-wise multiplication between **B** and **C** and store the result in array **D**.
  * **Step 6**: Take the non-zero elements in **D** and store into a new 1-D array **E**.
  * **Step 7**: Normalize the elements in **E** and store in **F** using equations:  
    ```Python
        max, min = E.max(), E.min()

    val_normalized = (val_original - min) / (max - min)
  * **Step 8**: Reshape array F into a 2-D square matrix G. The size of G should be the square root of the number of elements in F, rounded down to the nearest integer. 
  * **Step 9**: Calculate the dot product of matrix G with its transpose (i.e., G * G<sup>T</sup>) and store the result in a new matrix H.

In [449]:
import numpy as np

In [450]:
## Q1
A = np.zeros(shape=(9,6))
print(type(A))
print()
print(A.shape)

<class 'numpy.ndarray'>

(9, 6)


In [451]:
## Q2
# clear
A[:] = 0

# slice by row
A[:2, 1:-1] = 1
A[2:-2, 2:4] = 1
A[-2:, 1:-1] = 1

# print A
print(A)

[[0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]]


In [452]:
# Q3
# make arr B with two more rows, then insert A vectors at all indexes excluding first and last
B = np.zeros((A.shape[0] + 2, A.shape[1]))
B[1:(1 + A.shape[0])] = A

# print B
print(B)


[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [453]:
# Q4
print(B.shape)
print()
C = np.zeros(B.shape)

# parse C, fill C[index] = index + 1
for i in range(0, C.shape[0]):
    for j in range(0, C.shape[1]):
        C[i][j] = (i * C.shape[1]) + (j + 1)

# print
print(C)

(11, 6)

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30.]
 [31. 32. 33. 34. 35. 36.]
 [37. 38. 39. 40. 41. 42.]
 [43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54.]
 [55. 56. 57. 58. 59. 60.]
 [61. 62. 63. 64. 65. 66.]]


In [454]:
## Q5
# mult by element
D = B * C

# print
print(D)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  8.  9. 10. 11.  0.]
 [ 0. 14. 15. 16. 17.  0.]
 [ 0.  0. 21. 22.  0.  0.]
 [ 0.  0. 27. 28.  0.  0.]
 [ 0.  0. 33. 34.  0.  0.]
 [ 0.  0. 39. 40.  0.  0.]
 [ 0.  0. 45. 46.  0.  0.]
 [ 0. 50. 51. 52. 53.  0.]
 [ 0. 56. 57. 58. 59.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


In [114]:
## Q6
# load array E with nonzero elements of array D
E = D[D != 0]

# print
print(E)

[ 8.  9. 10. 11. 14. 15. 16. 17. 21. 22. 27. 28. 33. 34. 39. 40. 45. 46.
 50. 51. 52. 53. 56. 57. 58. 59.]


In [455]:
## Q7
# load array F with normalized elements of array E
min, max = E.max(), E.min()
F = np.zeros(E.shape)

F = (E - min) / (max - min)

# print
print(F)

[ 1.          0.98039216  0.96078431  0.94117647  0.88235294  0.8627451
  0.84313725  0.82352941  0.74509804  0.7254902   0.62745098  0.60784314
  0.50980392  0.49019608  0.39215686  0.37254902  0.2745098   0.25490196
  0.17647059  0.15686275  0.1372549   0.11764706  0.05882353  0.03921569
  0.01960784 -0.        ]


In [116]:
## Q8
# load 2-D array G with shape(floor(sqrt(F.shape)))
# with elements F
import math

row_g = math.floor(math.sqrt(F.shape[0]))
G = np.zeros((row_g, row_g))

for i in range(0, G.shape[0]):
    for j in range(0, G.shape[1]):
        G[i][j] = F[i * G.shape[0] + j]

# print
print(G)

[[1.         0.98039216 0.96078431 0.94117647 0.88235294]
 [0.8627451  0.84313725 0.82352941 0.74509804 0.7254902 ]
 [0.62745098 0.60784314 0.50980392 0.49019608 0.39215686]
 [0.37254902 0.2745098  0.25490196 0.17647059 0.15686275]
 [0.1372549  0.11764706 0.05882353 0.03921569 0.01960784]]


In [456]:
## Q9
# load arary H with dot product of G and G_transpose
H = np.dot(G, G.T)

# print
print(H)

[[4.54863514 3.82199154 2.52056901 1.19108035 0.3633218 ]
 [3.82199154 3.21491734 2.12341407 1.00807382 0.30949635]
 [2.52056901 2.12341407 1.41714725 0.67858516 0.21453287]
 [1.19108035 1.00807382 0.67858516 0.3348712  0.10841984]
 [0.3633218  0.30949635 0.21453287 0.10841984 0.03806228]]


## PART II: More Python: Image Processing

With the basic knowledge of NumPy, we will move on to play with some images in the form of NumPy arrays. You may find these two packages helpful in this part: [pillow][pillow_doc] and [matplotlib][matplotlib_doc]. Pillow is an image library for python. It is capable of handling many image-processing related tasks. Matplotlib is a commonly used package for plotting graphs and images in python. We should only be using some very basic functions of those two libraries in the following tasks. 

**In your report, you should show the resulting images of each step.**

  * **Step 1**: Read the image from `'figures/tulips.png'`, and convert it into a NumPy array. Print the type and the shape of the array. Display the array (which has been converted from the image). You can use [Image.open(...)][Image_open_doc] function from the pillow package to read the image and use [imshow(...)][imshow_doc] from the matplotlib package to display the cropped image (refer to **Step 2**). Notice that each pixel is represented by an integer number ranging from 0 to 255 in the output of `Image.open(...)`, so you may need to normalize pixel values to range [0.0, 1.0] (floating points) to make sure all pixels' values are still within the valid range after we apply the filters in following steps. Be careful, the image has three channels, which represent Red, Green and Blue respectively.

[pillow_doc]:https://pillow.readthedocs.io/en/stable/
[matplotlib_doc]:https://matplotlib.org/index.html
[Image_open_doc]:https://pillow.readthedocs.io/en/stable/reference/Image.html
[imshow_doc]:https://matplotlib.org/3.3.3/api/_as_gen/matplotlib.pyplot.imshow.html

In [457]:
### import the packages and functions here ###
### your code goes here ###
import numpy as np
from PIL import Image

# grab image, load np_array img_arr
with Image.open('figures/tulips.png') as img:
    #img.show()
    img_arr = np.array(img.getdata())
#print(img_arr)

# nomalize img_arr values
min, max = 0, 255
img_arr_norm = np.zeros(img_arr.shape)

img_arr_norm = (img_arr - min) / (max - min)

# print
print(img_arr[0])
print(img_arr_norm[0])

[ 54 101  83]
[0.21176471 0.39607843 0.3254902 ]


  * **Step 2**: Center-crop the image into dimension (200, 200, 3), meaning that you should crop the central portion of the image to the target height and width. For example:
  ![center_crop_img](figures/center-crop.jpg)

In [461]:
### import the packages and functions here ###
### your code goes here ###
cropped_width = 200
cropped_height = cropped_width

cropped_left = (img.width / 2) - (cropped_width / 2)
cropped_top = (img.height / 2) - (cropped_height / 2)
cropped_right = cropped_left + cropped_width
cropped_bottom = cropped_top + cropped_height

cropped_list = [cropped_left, cropped_top, cropped_right, cropped_bottom]
img_cropped = img.crop(cropped_list)

# print
img_cropped.show()
img.show()

  * **Step 3**: We will then apply filters to the processed image. In order to preserve the orginial dimensions (H, W, C) of the image after the filtering, we need to properly pad the image first. Similar to **PART I Step 3**, pad the image with zeros on all four edges. You can use [pad(...)][pad_doc] function from the numpy pacakge to do this.

[pad_doc]:https://numpy.org/doc/stable/reference/generated/numpy.pad.html

In [462]:
### import the packages and functions here ###
### your code goes here ###
import math

img_padded = Image.new(img.mode, (img.width, img.height), (0, 0, 0))
img_padded.paste(img_cropped, (math.floor(cropped_left), math.floor(cropped_top)))

img_padded.show()

  * **Step 4**: 2-D convolution is one of the very basic of operations of image processing. The 2-D convolution of a filter on an image is the operation of multiplying each pixel in the overlapping portion of the "sliding window" and then add these pixels together to make one output pixel. There is an excellent video explainning the basics [here][2d_conv_video]. You may read more [here][2d_conv]. 
    The pseudocode is shown below:
    ```
    for row in # of rows of output:
        for col in # of columns of output:
            for ch in # of channels of input/output:
                sum = 0
                for kh in # rows of filter:
                    for kw in # columns of filter:
                        sum += input[row+kh][col+kw][ch] * filter[kh][kw]
                output[row][col][ch] = sum
    ```
    
    It it important to note that this pseudocode is slightly different from what a convolution looks like in a Convolutional Neural Network (CNN). The difference comes from how we apply the filters. We will talk more about the convolutions in CNN later in the course. 
    
    Now, use the following filters to process the original picture and display the results. **You should write your own 2-D convolution kernel code derived from the above pseudocode instead of using existing pre-written conv functions from any packages.**
    
    As a side note, the original image has three channels, and you should apply the filter to each of the three channels separately.
 
    1. Gaussian Blur
    ``` Python
gaussian_filter = np.asarray([
    [1,  4,  6,  4,  1],
    [4, 16, 24, 16,  4],
    [6, 24, 36, 24,  6],
    [4, 16, 24, 16,  4],
    [1,  4,  6,  4,  1]
], dtype=np.float32)
gaussian_blur = gaussian_filter/np.sum(gaussian_filter)
    ```
    2. Motion Blur
    ``` Python
motion_filter = np.asarray([
    [1, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 1],
], dtype=np.float32)
motion_blur = motion_filter/np.sum(motion_filter)
    ```
    3. Edge Detection
    ``` Python
edge_filter = np.asarray([
  [-1, -1, -1],
  [-1,  8, -1],
  [-1, -1, -1]
], dtype=np.float32)
    ```
[2d_conv_video]:https://www.youtube.com/watch?v=C_zFhWdM4ic
[2d_conv]:https://www.allaboutcircuits.com/technical-articles/two-dimensional-convolution-in-image-processing/


In [463]:
### import the packages and functions here ###
### your code goes here ###
### Part 1 Define a convolution function
def conv_2d(input, filter):
    num_kh, num_kw = filter.shape
    num_row, num_col, num_ch = input.shape

    output = np.zeros((input.shape), dtype=input.dtype)

    print(input.shape)
    print(output.shape)
    print(filter.shape)

    for row in range(0, num_row - num_kh):
        for col in range(0, num_col - num_kw):
            for ch in range(0, num_ch):
                sum = 0
                for kh in range(0, num_kh):
                    for kw in range(0, num_kw):
                        # if (row + kh >= num_row ):
                        #     break
                        # if (col + kw >= num_col ):
                        #     break
                        sum = sum + (input[row + kh][col + kw][ch] * filter[kh][kw])
                output[row][col][ch] = sum
    return output

In [464]:
### Part 2 Apply the Gaussian filter
gaussian_filter = np.asarray([
  [1,  4,  6,  4,  1],
  [4, 16, 24, 16,  4],
  [6, 24, 36, 24,  6],
  [4, 16, 24, 16,  4],
  [1,  4,  6,  4,  1],
], dtype=np.float32)
gaussian_blur = gaussian_filter/np.sum(gaussian_filter)
### import the packages and functions here ###
### your code goes here ###
img_padded_arr = np.asarray(img_padded)

gaussian_blur_output_arr = conv_2d(img_padded_arr, gaussian_blur)

#print(gaussian_blur_output_arr)
print(np.count_nonzero(img_padded_arr))
print(np.count_nonzero(gaussian_blur))
print(np.count_nonzero(gaussian_blur_output_arr))

img_gaussian_blur = Image.fromarray(gaussian_blur_output_arr)
img_gaussian_blur.show()

(512, 768, 3)
(512, 768, 3)
(5, 5)
119600
25
124830


In [465]:
### Part 3 Apply the Motion Blur filter
motion_filter = np.asarray([
    [1, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 1],
], dtype=np.float32)
motion_blur = motion_filter/np.sum(motion_filter)
### import the packages and functions here ###
### your code goes here ###
img_gaussian_blur_arr = np.asarray(img_gaussian_blur)

motion_blur_output_arr = conv_2d(img_gaussian_blur_arr, motion_blur)

img_motion_blur = Image.fromarray(motion_blur_output_arr)
img_motion_blur.show()


(512, 768, 3)
(512, 768, 3)
(7, 7)


In [466]:
### Part 4 Apply the Edge Detection filter
edge_filter = np.asarray([
  [-1, -1, -1],
  [-1,  8, -1],
  [-1, -1, -1]
], dtype=np.float32)
### import the packages and functions here ###
### your code goes here ###
img_motion_blur_arr = np.asarray(img_motion_blur)

edge_filter_output_arr = conv_2d(img_motion_blur_arr, edge_filter)

img_edge_filter = Image.fromarray(edge_filter_output_arr)
img_edge_filter.show()

(512, 768, 3)
(512, 768, 3)
(3, 3)


 * **Step 5**: Now you should pick filter(s) to apply advanced image processing techniques to enhance specific features of an image. This technique is often used to enhance details and sharpen images.
    1. First, apply a blur to the original image $X$. Store this as Blurred Image.
    2. Subtract the Blurred Image from the original image to get a Detail Enhancement image ($\Delta = X - F(X)$).
    3. Add the Detail Enhancement image back to the original image to produce a Sharpened Image ($\Delta + X$).
    4. Display the Blurred Image, Detail Enhancement image, and the final Sharpened Image.
    
    By displaying each picture in the process (three images in total), you may observe the effect of sharpening.

In [467]:
### import the packages and functions here ###
### your code goes here ###
### Step 5: Image Sharpening
img_x = img
img_x_arr = np.asarray(img_x)
blurred_arr = conv_2d(img_x_arr, motion_blur)
img_blurred = Image.fromarray(blurred_arr)

# img_x_arr_output is 'Blurred Image'
# subtracted 'Blurred Image' from original to get delta
delta_arr = img_x_arr - blurred_arr
img_delta = Image.fromarray(delta_arr)

# add delta to original to get sharp image
sharp_arr = delta_arr + img_x_arr

# convert sharp_arr to image
img_sharp = Image.fromarray(sharp_arr)


(512, 768, 3)
(512, 768, 3)
(7, 7)


In [468]:

# print
#img_x.show()
img_blurred.show()
img_delta.show()
img_sharp.show()



 * **Step 6**: Also, we often need to downscale an image. We will use a basic algorithm to accomplish this: Gaussian pyramid. You can read about this technique [here][pyramid]. In this step, you will downsample the given image twice, each with a factor of two. In other words, you will first shrink the image to half of the size (2X smaller), then shrink it again by 2X. As a result, you will have an image that is one-fourth of its original size (4X smaller). We will try two approaches and see the difference.
    1. Naive downsampling: you simply pick the 2nd, 4th, 6th, ..., nth pixels (every two pixels) by skipping one pixel each time. The resulting image should have one half of the size of the original. You repeat this process to obtain the 1/4 size image.
    2. Gaussian pyramid: You apply the Gaussian filter to the image first, like what you have done in the previous step. After that, you downsample on the filtered image. Again, you pick the 2nd, 4th, 6th, ..., nth pixels by skipping one pixel each time when you downsample. Then, you repeat this process of "filter and downsample" to obtain the 1/4 size image. The Gaussian filter removes the high-frequency components from the image before downsampling, thus avoiding the aliasing problem as you will notice in the results.
    
    By displaying each picture in the process (two downsampled images per approach, four images in total), you may observe some difference in the results of the two techniques.
[pyramid]:https://en.wikipedia.org/wiki/Pyramid_(image_processing)#:~:text=pyramid%20generation%20steps.-,Gaussian%20pyramid,lower%20level%20of%20the%20pyramid.

In [471]:
### import the packages and functions here ###
### your code goes here ###
### Part 1 Naive downsampling
img_arr = np.asarray(img)
downsize_arr = np.array( (math.floor(img_arr.shape[0] / 2), math.floor(img_arr.shape[1] / 2), img_arr.shape[2]) )

downsize_arr = img_arr[::2, ::2, :]

downsize2_arr = np.array( (math.floor(downsize_arr.shape[0] / 2), math.floor(downsize_arr.shape[1] / 2), downsize_arr.shape[2]) )

downsize2_arr = downsize_arr[::2, ::2, :]

img_downsize = Image.fromarray(downsize2_arr)

In [472]:
# print
img.show()
img_downsize.show()

In [473]:
### import the packages and functions here ###
### your code goes here ###
### Part 2 Gaussian filter + downsampling
img_y = img
img_y_arr = np.asarray(img_y)
gaussian_img_y = conv_2d(img_y_arr, gaussian_blur)

downsize_arr = gaussian_img_y[::2, ::2, :]

downsize_arr = conv_2d(downsize_arr, gaussian_blur)

downsize2_arr = downsize_arr[::2, ::2, :]

img_downsize = Image.fromarray(downsize2_arr)

(512, 768, 3)
(512, 768, 3)
(5, 5)
(256, 384, 3)
(256, 384, 3)
(5, 5)


In [129]:
# print
img.show()
img_downsize.show()

## PART III: HTTP Communication, KNN and K-means in Python

In this part of the lab, we will implement a system that communicates with a server to acquire test data and perform [k-nearest neighbor][knn] (KNN) classification and K-means clustering on your computer.

The overall operation of the classification system is depicted in the following figure:

<!-- ![server_img](figures/server_behavior.svg) -->
<img src="figures/server_behavior.svg" width="60%">

The system works in a [RESTful][RESTful_tutorial]-like manner, and there are five main steps in the whole process:
1. **Request for data**
   The user sends an HTTP request with a specific body content to request a set of testing samples to be classified.
2. **Receive data**
   Upon receiving the request, the server will generate five random test IDs and select these samples from the testing dataset. Then, it sends back the test samples as a text string in comma-separated values (CSV) format in the response, and each sample will have a unique test ID and four separate features to be used for inference. For this part of the lab, we will use the classic [Iris dataset][iris_wiki]. The dataset is already randomly split into training and testing datasets. The training dataset will be provided to you, and the testing dataset will be stored on the server.
3. **Local inference**
   The local system parses the CSV file and performs the inference on the five input samples with kNN, which will be trained on the training dataset provided to you.
4. **Send results**
   Once the classes of the five samples are determined, create a new `POST` request with the test ID and the results and send them to the server for verification.
5. **Return verification**
   Upon receiving the request, the server will first use the test IDs to find the ground truth labels of the test samples and compare them with the ones from the `POST` request. Finally, the server sends back, in the response, a number indicating the number of correct classifications.

As introduced in the lecture, KNN is a classic machine learning algorithm that does not assume pre-defined parameters or data distributions. K is the number of nearest neighbors. When k = 1, the algorithm is simply the nearest neighbor algorithm. Intuitively, in the nearest neighbor algorithm, the unknown data point is classified as the same label as the known data point from which it has the least distance in the hyperspace, as shown in the following picture. 

![knn_k1_img](figures/knn_k1.png)

In the k-nearest neighbor algorithm, you pick k data points that are closest to the unknown data. The k known data points make a collective decision on which label the unknown data should be assigned. The following three pictures show the process. 

![knn_k_img](figures/knn_k.png)

<sup>(picture source: https://www.datacamp.com/community/tutorials/k-nearest-neighbor-classification-scikit-learn)</sup>

On the other side, K-means clustering is one of the most popular unsupervised machine learning algorithms. The K-means algorithm in data mining starts with a K group of randomly selected centroids, which are used as the beginning points for every cluster, and then performs iterative (repetitive) calculations to optimize the positions of the centroids. The process is shown in the following picture.

It halts creating and optimizing clusters when either:

1. The centroids have stabilized — there is no change in their values because the clustering has been successful.
2. The defined number of iterations has been achieved.

<img src="figures/kmeans.png" width="500" height="500">
<!-- ![kmeans_img](figures/kmeans.png).size(0.5) -->

<sup>(picture source: https://towardsdatascience.com/k-means-a-complete-introduction-1702af9cd8c)</sup>

**Important**: You should only use the Python packages that are introduced in this lab: NumPy, Requests, and Pandas. You may use some plotting packages to visualize the datasets if you feel extra fancy. However, you should not use any machine learning packages such as scikit-learn.

[RESTful_tutorial]:https://restfulapi.net/
[knn]:https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm
[iris]:https://courses.grainger.illinois.edu/ece479/sp2023/secure/labs/lab1/iris_train.csv
[iris_label]:https://courses.grainger.illinois.edu/ece479/sp2023/secure/labs/lab1/iris_label.csv
[iris_wiki]:https://en.wikipedia.org/wiki/Iris_flower_data_set


* **Step 1**: Download the Iris dataset from [here][iris] and the labels from [here][iris_label]. Read the csv datasets into arrays. You may use the following code:

    ``` Python
import pandas as pd
data = pd.read_csv('iris.csv', header=0, names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
labels = pd.read_csv('iris_labels.csv', header=0, names=['label'])
    ```
[iris]:https://courses.grainger.illinois.edu/ece479/sp2024/secure/labs/lab1/iris_train.csv
[iris_label]:https://courses.grainger.illinois.edu/ece479/sp2024/secure/labs/lab1/iris_train_label.csv

In [477]:
### import the packages and functions here ###
### your code goes here ###
import pandas as pd
data = pd.read_csv('data/iris.csv', header=0, names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
labels = pd.read_csv('data/iris_label.csv', header=0, names=['label'])

print(data)
print(labels)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]
         label
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]


  * **Step 2**: Make a `POST` request with the following specifications:

    ``` Python
url = 'http://courses.grainger.illinois.edu/ece479/sp2024/lab1_request_dataset.php'
body = {'request': 'testdata'}
    ```
    Please read the first three sections of [guide](https://requests.readthedocs.io/en/master/user/quickstart/) to learn how to send HTTP requests and parse responses from the server.
    Also, make sure that you make request to `https` (SSL certificated) instead of `http`. If your request is properly made, the server should return a content in comma-separated values (CSV) format. Parse the content into an array, and this array will be used as your testing dataset in the following steps. 

In [480]:
### import the packages and functions here ###
### your code goes here ###
import requests
import re

url = 'https://courses.grainger.illinois.edu/ece479/sp2024/lab1_request_dataset.php'
body = {'request': 'testdata'}
r = requests.post(url, body)

r_temp = re.split(',|\n', r.text)
testdata_arr = np.zeros((5, 5))

for i in range(0, 5):
    for j in range(0, 5):
        testdata_arr[i][j] = r_temp[(i + 1) * 5 + j]
print(testdata_arr)

[[ 1.   5.7  3.8  1.7  0.3]
 [ 3.   6.   2.9  4.5  1.5]
 [ 8.   6.2  2.2  4.5  1.5]
 [11.   4.8  3.   1.4  0.1]
 [14.   5.1  3.8  1.5  0.3]]


* **Step 3**: We will use the Euclidean distance to find the nearest neighbors. Write a function that calculates the distance between two data points. Note: each data point has four features, which means each $X$ is a four-dimensional variable. Recall that the Euclidean distance is defined as $\sqrt{\sum_{i=1}^{N=4}(x^{(i)}_1-x^{(i)}_2)^2}$. 
  
  **Hint**: this can be easily done as a one-liner with Numpy, try to avoid using nested loops.

In [198]:
### import the packages and functions here ###
### your code goes here ###
import math

# B input in pd.dataframe iterrow object
def dist(A, B):
    sum = 0
    for i in range(1, 5):
        sum += ((A[i] - B[1][i - 1])**2)
    return math.sqrt(sum)

* **Step 4**: Implement a function that predicts the classes of the five testing samples using kNN. To perform kNN for a testing sample, first calculate the Euclidean distances between the testing sample and all the samples in the training dataset that are given to you. Then, rank the training samples by their distances to the testing sample, and find the k points that have the least distances to the testing sample. Finally, take the most common labels of the k nearest neighbors and use that to classify the unknown testing data point. 
    You may experiment with different values of k to see if they give you different answers. We recommend that you try k = 3, 5, or 7.

In [440]:
### import the packages and functions here ###
### your code goes here ###
def classify_k(test_set):
     k = 5
     prediction = []

     for test_point in test_set:
          # fetch curr train point data
          distance = np.asarray([dist(test_point, train_point) for train_point in data.iterrows()])

          # sort distances, get k nearest neighbors
          nearest_idx = np.argsort(distance)[:k]\

          # make list of corresponding labels
          nearest_label = []
          for idx in nearest_idx:
               label = labels.loc[idx]['label']
               nearest_label.append(label)

          flower_a, flower_b, flower_c = 0, 0, 0
          for label in nearest_label:
               if (label == "versicolor"):
                    flower_a += 1
               elif (label == "setosa"):
                    flower_b += 1
               elif (label == "virginica"):
                    flower_c += 1
               else:
                    print("bad match")
                    return
          nearest_label.clear()
                    
          if (flower_a > flower_b and flower_a > flower_c):
               prediction.append("versicolor")
          elif (flower_b > flower_a and flower_b > flower_c):
               prediction.append("setosa")
          elif (flower_c > flower_a and flower_c > flower_b):
               prediction.append("virginica")

     # return predictions
     # format for json
     str = ','.join(prediction)
     prediction.clear()
     return str

* **Step 5**: Make a `POST` request again to the same URL. This time, the `request` field will be `verify`, and you should specify the two additional `test_ids` and the `predictions` fields. They should be in the form of ',' deliminated list, i.e. \"1,3,5,6,7\" for the `test_ids`. The structure of your request should be like the following:
```python
    {'request':'verify',
     'test_ids':'1,3,6,8,12',
     'predictions':'setosa,setosa,versicolour,virginica,setosa'}
```
The server will return the number of correct predictions on the testing samples drawn from the testing dataset. The accuracy should be 100% in most cases.

In [481]:
### import the packages and functions here ###
### your code goes here ###
url = 'https://courses.grainger.illinois.edu/ece479/sp2024/lab1_request_dataset.php'
body = {'request': 'testdata'}

r = requests.post(url, body)

r_temp = re.split(',|\n', r.text)

print(r.text)
print()

for i in range(0, 5):
    for j in range(0, 5):
        testdata_arr[i][j] = r_temp[(i + 1) * 5 + j]

testdata_ids = ','.join(r_temp[5::5])
testdata_prediction = classify_k(testdata_arr)

print(testdata_ids)
print(testdata_prediction)

### VERIFY ###
body = {'request': 'verify',
        'test_ids': testdata_ids,
        'predictions': testdata_prediction} 

r = requests.post(url, body)

print()
print(r.text, " out of ", len(testdata_arr[:, 0]))


test_id,sepal_length,sepal_width,petal_length,petal_width
1,5.7,3.8,1.7,0.3
5,5.4,3.4,1.5,0.4
7,6.9,3.1,5.1,2.3
10,6.5,3.2,5.1,2
12,5.5,3.5,1.3,0.2

1,5,7,10,12
setosa,setosa,virginica,virginica,setosa

5  out of  5


* **Step 6**: Implement a function that finds the k centroids of the iris dataset using K-means. To perform K-means for a dataset, first, initialize random k centroids. Then for each data point, find the nearest euclidean distance to centroids and assign the point to that cluster. In addition, for each cluster, compute the new centroid equals the mean of all points assigned to that cluster. You should repeat the distance calculation, and centroids update until convergence or until the end of a fixed number of iterations. We recommend that you try k = 2, 3, or 4.

In [ ]:
def find_centroids(arr, centroids):
    ##
    k = 3
    ##

    idx = np.zeros(arr.shape[0], dtype = int)
    for curr_point in arr.shape[0]:
        distance = np.asarray([distance(curr_point, point) for point in centroids.iterrows()])
        idx[i] = np.argsort(distance)[:k]

    return idx

In [15]:
### import the packages and functions here ###
### your code goes here ###
def k_means(arr, init_centroids):
    ##
    num_loop = 10
    k = 3
    ##

    # init
    m, n = arr.shape
    centroids = init_centroids
    prev_centroids = centroids
    idx = np.zeros(m)

    ###
    for i in range(num_loop):
        idx = find_centroids(arr, centroids)


## Report Requirements: (10 pts)
You have to do a live demo for this lab during your designated lab session. In addition, you will need to turn in a report and the code. **We highly recommend that you directly use the provided Jupyter Notebook and turn it in as a combination of the report and the code.**

### Part 1: (2 pts)
* Show the code and the results of each step. Discuss your approaches for correct generations of all NumPy arrays **A** to **G**, with each worth 0.25 points.
* Since the code should be very short, you can either type it directly in the report or take screenshots of both the code and the resulting arrays and paste the screenshot into the report.
  
### Part 2: (3 pts)
* Show the results of each step. Discuss your appoarches. There is no need to include the code in the report. 
* For step 1, show the type and the shape of the array, print the original image. For step 2, show the cropped image. Nothing needs to be shown for step 3. The whole step 1 to 3 worth 1 point. 
* For step 4, show the resulting images of the three filtering processes. Step 4 worths 1 point.
* For step 5, show the three images for three steps. Step 5 worths 0.5 point.
* For step 6, show the four images from the two different approaches. Step 6 worths 0.5 point.

  
### Part 3: (5 pts)
* Show the results of each step. Discuss your appoarches. There is no need to include the code in the report. 
* For step 1, print the data you read from both csv files. For step 2, acquire at least 3 datasets from the server and print the response. You may take screenshots to show the prints. Step 1 and 2 worth 1 point.
* For step 3 and 4, briefly discuss your code, including what k values that you have tried. Show a screenshot of the two functions if they can be contained in one page. The code shouldn't be very long. Step 3 and 4 worth 2 points.
* For step 5, print the responses from the server. Step 5 worths 1 point.
* For step 6, print the centroid values of k=3. Step 6 worths 1 point.


### Notes: 
* Besides the above requirements, your report should also include the following details: 
  * Your full name and your NetID.
  * The difficulties/bugs you encountered and how you solved them
  * What you learned from this lab
* Your report should cover all the required information, but please keep your report clean and concise.
* Please add references to your report if you referred to any resources when you work on your lab.

